name: Syntax Check

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      uses: fdiblen/anaconda-action@0.1.20

